#!/bin/bash
# Author: echoenzo
# Tests solution with name $filename against sample data downloaded from open.kattis.com

filename=$1
problem=$(echo "$filename" | tr "[:upper:]" "[:lower:]")

if [ -d ~/Projects/kattis/java/"$problem" ]; then
    directory=~/Projects/kattis/java/"$problem"
    cd "$directory" || exit
    javac ./*.java
    if [ -d samples/ ]; then
        x=1
        for i in samples/*.in; do
            touch 'output'
            java "$filename" < "$i" > output
            if grep -Fqxvf output "${i:0:-3}".ans; then
                echo 'TEST '${x}': FAIL'
            else
                echo 'TEST '${x}': PASS'
            fi
            rm output
            x=$((x+1))
        done
    else
        echo 'There are no sample files to test!'
    fi
else
    echo 'No such file to test.'
fi
